name: CI Stage
on:
  pull_request:
    branches: [main]
    types: 
      - closed
env:
  TAG: v0.0.5
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go version
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Publish version
        shell: bash {0}
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "Nothing to publish";
          else
            git tag $TAG;
            git push origin $TAG;
            echo 'Version '"$TAG"' published'
          fi
