name: CI Stage
on: [ push ]
env:
    TAG: v0.0.3
jobs:  
  build:    
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup Go version
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache stack images
      id: cache-docker
      uses: actions/cache@v3
      env:
        cache-name: cache-services
      with:
        path: |
          ~/stack-images
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack-docker-compose.yml') }}
    - if: ${{ steps.cache-docker.outputs.cache-hit == 'true' }}
      name: Import stack images
      timeout-minutes: 5
      run: |
        docker load < ~/stack-images/zookeeper.tar
        docker load < ~/stack-images/kafka.tar
        docker load < ~/stack-images/schema-registry.tar

    - name: Build stack
      run: docker-compose -f stack-docker-compose.yml up -d
    - name: Run tests
      run: go test ./...
    - name: Publish version
      shell: bash {0}
      run: |
        git fetch origin
        CURRENT_TAG=$(git tag -l | grep "$TAG");
        if [[ -z "$CURRENT_TAG" ]]; then
          # git tag $TAG;
          # git push origin $TAG;
          echo 'Version '"$TAG"' published'
        else
          echo "Nothing to publish";
        fi

    - if: ${{ steps.cache-docker.outputs.cache-hit != 'true' }}
      name: Export stack images
      timeout-minutes: 5
      run: |
        mkdir ~/stack-images
        cd ~/stack-images
        docker save --output="zookeeper.tar" confluentinc/cp-zookeeper
        docker save --output="kafka.tar" confluentinc/cp-kafka
        docker save --output="schema-registry.tar" confluentinc/cp-schema-registry
