name: CI Stage
on:
  push:
    branches: [ actions ]
env:
    TAG: v0.0.3
jobs:  
  build:    
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup Go version
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    # - name: Build stack
    #   run: docker-compose -f stack-docker-compose.yml up -d
    # - name: Run tests
    #   run: go test ./...
    - name: Publish version
      shell: bash {0}
      run: |
        currentTag=$(git fetch origin | git tag -l | grep "v0.0.3");
        echo 'asd '"$currentTag"' asd '"$TAG";
        if [[ -z "$currentTag" ]]; then
          # git tag $TAG;
          # git push origin $TAG;
          echo 'Version '"$TAG"' published'
        else
          echo "Nothing to publish";
        fi
